### ISSUE TITLE
UNC paths are not supported

### ISSUE THREAD

**Issue by JoppeJoppinger** [bramerdaniel/ConsoLovers#20]
Our team really loves to use ConsoLovers, but unluckily, there is a small bug in method

`private CommandLineArgument ParseSingleArgument(string argument, int index)`

the following code destroys an UNC argument: 

```
 if (charInfo.Current == '\\' && (charInfo.Next == '\\' || charInfo.Next == '"'))
               return;
```

Is it possible write it like this? 
```
if (charInfo.Current == '\\' && charInfo.Next == '"')
               return;
```

Thank you for your great work!
El Mano, espanol

**Comment by bramerdaniel** [comment]
As I am planing to make a new release, I would fix the problem if you could provide some sample data (UNC paths that should work in your oppinion), so that I can ensure the behaviour with unit tests.

And also how you specified the arguments class.

Thanks Danielito, italiano

**Comment by bramerdaniel** [comment]
Fixed
