### ISSUE TITLE
Implement additional console keyboard hook to mask password chars.

### ISSUE THREAD

**Issue by ats-ccochran** [bramerdaniel/ConsoLovers#3]
Love the toolkit. Was creating an extension to your sample and could use a masking characters option for the console similar to this: http://www.codeproject.com/Articles/8110/NET-Console-Password-Input-By-Masking-Keyed-In-Ch

`        public static void SignIn(ConsoleMenuItem sender)
        {
            string password = String.Empty;

            Console.WriteLine("Enter your username:\n");
            userName = Console.ReadLine();

            Console.WriteLine("Enter your password:\n");

            // Mask the console input here.
            sender.Menu.KeyboardOptions.MaskInput("*");

            password = Console.ReadLine();
            
            sender.Menu.KeyboardOptions.ResetToDefault();

            // Check username/Password validity
        }`

**Comment by bramerdaniel** [comment]
Thanks for your compliment,

Im not sure if the functionality of masking the input of the console should be part of the ConsoleMenu class,  but if you would share your code ( or create a pull request) I will try to find a way to include this functionality into the toolkit.

The toolkit will get more features in the future. I allready have some good ideas, but I will also try to integrate good Ideas from the users of the toolkit (If there are).

So feel free to write more issues or wishes if you have good ideas, or functionality you are missing in existing classes.

Daniel

**Comment by bramerdaniel** [comment]
Added a new class called InputMask that should do the same.
Usable something like this:

```
     Console.Write("Enter your password : ");
     var mask = '*';
     var length = 8;
     var placeHolder = '.';
     var password = new InputMask().ReadLine(mask,length, placeHolder);
     Console.WriteLine($"Password: {password}");
```

[https://github.com/bramerdaniel/ConsoLovers/blob/master/ConsoLovers/InputMask.cs](url)

Daniel

**Comment by ats-ccochran** [comment]
Daniel, 

```
Thanks, I'll take a look at it and see if it works for this use case. 
```

Thanks,
Chris

**Comment by ats-ccochran** [comment]
Daniel, 

```
I ran the playground project and played with it. It works perfectly! I'll implement it in my project this weekend and close this ticket once completed.
```

Thanks!
Chris
