### ISSUE TITLE
InputBox second constructor parameter shoud be object

### ISSUE THREAD

**Issue by bramerdaniel** [bramerdaniel/ConsoLovers#7]
For easily providing default values, the second constructor parameter shoud be object.

A generic inputbox could also be a solution
var start = new InputBox<int>("StartIndex : ", 0).ReadLine();

**Comment by Pureaznangel** [comment]
I'm in agreement with you

**Comment by bramerdaniel** [comment]
Closed with version 5.0 (moved inputpox in ConsoLovers.ConsoleToolkit.Core)
